locals {
  location_slug = lookup(zipmap(values(local.regions), keys(local.regions)), var.aws_region, lookup(zipmap(values(local.cli_names), keys(local.cli_names)), var.aws_region, var.aws_region))

  # AWS region mapping between slug and standard format.

  regions = {
    us-east-2      = "US East (Ohio)"
    us-east-1      = "US East (N. Virginia)"
    us-west-1      = "US West (N. California)"
    us-west-2      = "US West (Oregon)"
    af-south-1     = "Africa (Cape Town)"
    ap-east-1      = "Asia Pacific (Hong Kong)"
    ap-southeast-3 = "Asia Pacific (Jakarta)"
    ap-south-1     = "Asia Pacific (Mumbai)"
    ap-northeast-3 = "Asia Pacific (Osaka)"
    ap-northeast-2 = "Asia Pacific (Seoul)"
    ap-southeast-1 = "Asia Pacific (Singapore)"
    ap-southeast-2 = "Asia Pacific (Sydney)"
    ap-northeast-1 = "Asia Pacific (Tokyo)"
    ca-central-1   = "Canada (Central)"
    eu-central-1   = "Europe (Frankfurt)"
    eu-west-1      = "Europe (Ireland)"
    eu-west-2      = "Europe (London)"
    eu-south-1     = "Europe (Milan)"
    eu-west-3      = "Europe (Paris)"
    eu-north-1     = "Europe (Stockholm)"
    me-south-1     = "Middle East (Bahrain)"
    me-central-1   = "Middle East (UAE)"
    sa-east-1      = "South America (Sao Paulo)"
  }

  short_names = {
    "us-east-2"      = "ue2"
    "us-east-1"      = "ue1"
    "us-west-1"      = "uw1"
    "us-west-2"      = "uw2"
    "af-south-1"     = "as1"
    "ap-east-1"      = "ae1"
    "ap-southeast-3" = "asw1"
    "ap-south-1"     = "as1"
    "ap-northeast-3" = "ane1"
    "ap-northeast-2" = "ane2"
    "ap-southeast-1" = "ase1"
    "ap-southeast-2" = "ase2"
    "ap-northeast-1" = "ane1"
    "ca-central-1"   = "cc1"
    "eu-central-1"   = "ec1"
    "eu-west-1"      = "ew1"
    "eu-west-2"      = "ew2"
    "eu-south-1"     = "es1"
    "eu-west-3"      = "ew3"
    "eu-north-1"     = "en1"
    "me-south-1"     = "ms1"
    "me-central-1"   = "mc1"
    "sa-east-1"      = "se1"

  }

  cli_names = {
    "us-east-2"      = "eastus2"
    "us-east-1"      = "eastus1"
    "us-west-1"      = "westus1"
    "us-west-2"      = "westus2"
    "af-south-1"     = "southafrica"
    "ap-east-1"      = "eastapac"
    "ap-southeast-3" = "southeastapac"
    "ap-south-1"     = "southapac"
    "ap-northeast-3" = "northeastapac3"
    "ap-northeast-2" = "northeastapac2"
    "ap-southeast-1" = "southeastapac1"
    "ap-southeast-2" = "southeastapac2"
    "ap-northeast-1" = "northeastapac1"
    "ca-central-1"   = "centralcanada"
    "eu-central-1"   = "centraleurope"
    "eu-west-1"      = "westeurope1"
    "eu-west-2"      = "westeurope2"
    "eu-south-1"     = "southeurope"
    "eu-west-3"      = "westeurope3"
    "eu-north-1"     = "northeurope"
    "me-south-1"     = "southmiddleeast"
    "me-central-1"   = "centralmiddleeast"
    "sa-east-1"      = "southamerica"
  }
}
